### ISSUE TITLE
PyPi

### ISSUE THREAD

**Issue by torstenfeld** [KronosKoderS/py_pushover#27]
Hi, are there any plans to release this module via PyPi. I'd highly appreciate it. And thanks for your great work!

**Comment by KronosKoderS** [comment]
Yes there is. I plan on trying to get it up and running by the end of the week.  I was hoping to get a few more improvements to the testing before releasing but I've run into a few snafus.

**Comment by KronosKoderS** [comment]
I just pulled the trigger.  Installation is now supported via PyPi using the `pip install py_pushover` command.

**Comment by torstenfeld** [comment]
Cool! Thanks a lot, @KronosKoderS !

**Comment by KronosKoderS** [comment]
@torstenfeld Just as an FYI, V1.0 #31 has been released, and uploaded to PyPi Servers.  Feel free to test and report any bugs you find.  Most basic usage however should have been tested by now and appears to be solid.
